# Generated by Django 5.0.6 on 2024-05-24 08:50

import django.db.models.deletion
import django.db.models.functions.datetime
import facturasieli.models.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("street", models.CharField(max_length=255)),
                ("addings", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.IntegerField()),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siret", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=255)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="facturasieli.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.IntegerField()),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "kind_of_payment",
                    models.CharField(default="Virement", max_length=255),
                ),
                ("name_provider", models.CharField(max_length=255)),
                ("name_client", models.CharField(max_length=255)),
                ("amount_excluding_tax", models.FloatField()),
                ("tax", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en attente", "en attente"),
                            ("vérifiée", "vérifiée"),
                            ("payée", "payée"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "client_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_as_client",
                        to="facturasieli.address",
                    ),
                ),
                (
                    "provider_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_as_provider",
                        to="facturasieli.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_at", models.DateField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Demande de facture"),
                            (2, "Facture soumise"),
                            (3, "Facture verifée"),
                            (4, "Facture réjétée"),
                            (5, "Facture payé"),
                        ],
                        default=1,
                    ),
                ),
                ("service_title", models.CharField(max_length=255)),
                (
                    "company_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_receiver",
                        to="facturasieli.company",
                    ),
                ),
                (
                    "company_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_sender",
                        to="facturasieli.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OTPModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "expiration_timestamp",
                    models.DateTimeField(
                        default=facturasieli.models.utils.compute_expiration_timestamp
                    ),
                ),
                ("otp", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="default_avatar.jpg",
                        upload_to=facturasieli.models.utils.get_avatar_path,
                    ),
                ),
                (
                    "last_request_timestamp",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("enable_2fa", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("issue_date", models.DateField()),
                ("intervention_start_date", models.DateField()),
                ("intervention_end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "Demande de facturation envoyé",
                                "Demande de facturation envoyé",
                            ),
                            ("Terminé", "Terminé"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_services",
                        to="facturasieli.company",
                    ),
                ),
                (
                    "company_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provided_services",
                        to="facturasieli.company",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="facturasieli.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("modification_date", models.DateField(auto_now=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="facturasieli.company",
                    ),
                ),
                (
                    "role",
                    models.ManyToManyField(
                        related_name="users", to="facturasieli.role"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
